version: '3'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    environment:
      - API_URL=http://api:8000
    volumes:
      - ../data:/app/data
    depends_on:
      - api
    restart: unless-stopped 